name: Linter

on:
    push:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16]

        steps:
            - uses: actions/checkout@v2
            - name: Linter
              run: |
                  npm install prettier -g
                  prettier --config ../../../prettierrc.js  --check "./**/*.ts"
                  prettier --config ../../../prettierrc.js  --check "./**/*.tsx"
